### ISSUE TITLE
Trying to create a switch in Home Assistant

### ISSUE THREAD

**Issue by appleimperio** [jneilliii/OctoPrint-MQTTSubscribe#38]
<img width="571" alt="Screenshot 2024-06-10 at 4 42 54 PM" src="https://github.com/jneilliii/OctoPrint-MQTTSubscribe/assets/72883739/0b40bea3-202a-45aa-8c39-1ac11530c830">

That's for turning on and off the switch basically a toggle that works fine

<img width="562" alt="Screenshot 2024-06-10 at 4 46 21 PM" src="https://github.com/jneilliii/OctoPrint-MQTTSubscribe/assets/72883739/59cd54e7-6ae2-455e-99b8-068fc372845e">

That one is for getting the status of the switch. I can turn it on and off but I don't get any status in home assistant

````
  {
  "status": 200,
  "response": {
    "status": false
  },
  "data": {
    "command": "getStatus",
    "subject": "r3"
  }
}
````
this is what I'm getting when it's off and the status changed to true when it's on
and this is my switch in HA

```
  switch:
    name: Nemo Filter
    unique_id: nemo_filter_mqtt_switch  
    command_topic: "nemo/filter/action"
    state_topic: "nemo/filter/status"
    state_on: "true"
    state_off: "false"
    optimistic: false
```

at this point I don't know if it's possible or I'm doing something wrong that I think it is.
